### ISSUE TITLE
[FEATURE] Add links to "Material Characterization" paper

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#10]
Links to be used in the tested building pages.

**Comment by mchaindl** [comment]
@ymarcon I just uploaded the new version of the database (.xlsx) to our shared drive. The link/s to the material characterization document is added for each building.
In some cases, there is more than one link for the material characterization and also in some cases, the link is the same as for the test paper. In any case, the links must be included (even if it is the same as the test paper)
