### ISSUE TITLE
[FEATURE] Massive download of numerical models

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#17]
@mchaindl Just like the test files, it could be possible to have a button to massively download the numerical models files from the Buildings page. Is this something that you are interested in?

**Comment by mchaindl** [comment]
@ymarcon For the moment, I would say it is better if we only allow downloading a full model only from the window of the model, but not massively from the Buildings page. I will discuss this here in the lab in more detail, so I can give you a final answer.
