### ISSUE TITLE
[Feat] Buldings page - Improving the test Pop-up 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#19]
Redesign the pop-up upon choosing a building, to simplify it and make it clearer that it is an intermediary dialog box leading to (a) Building test page or (b) Building numerical model page. The pop-up should contain : 

- [x] Title on top
- [x] Reference underneath (with links to the paper) + the full reference + "Other buildings from reference : (e.g. M1, M2 buttons etc) 
- [x] Motivation of the test
- [x] Buttons "View tests" and "View numerical model" should be merged with the images of test and numerical model below
- [x] Remove the table with the references details (too much info and redundant since there is link to the paper)
Do you agree @mchaindl ?

Small fixes 
- [x] : Order the buildings logically (e.g. M1, M2...)

**Comment by mchaindl** [comment]
@charlottegiseleweil I would include the reference details. I think is important to give more information about it to be sure that we are giving the proper credit to the authors, even if it is repeated later in the detailed window of the building.
