### ISSUE TITLE
[Feat] Buildings page design

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#20]
Design decisions

- [x] Rename page title (h6) : "Shake Table Tests & Models" and put it left of the toggle for Numerical models
- [x] Put explanatory text in a little (?) icon upon hover next to title
- [x] Update colorscheme 
-  Main colorscheme: EPFL red ? 
- Test data color : green ?
- Numercial model : blue (to match the 3D images blue?) 

Discussion for reference : 
### Filter for Numerical models
- Should we merge the Title line ("Buildings") and selectors line below ? 
- Should we have a clear legend with the icon "Numerical model available" or is the selector enough (Currently include the icon : )
<img width="279" alt="Screenshot 2024-05-16 at 09 19 46" src="https://github.com/EPFL-ENAC/eesd-mast/assets/18381609/eb0f66dc-a7dc-4e5a-b6f9-9d584b9ee163">

- Wording, should it say "Show only Buildings with numerical models"

- Is is okay like this, or did you really want the filter to appear also in the Filters left-menu ?

### Colorscheme coherence 

- Main colorscheme (currently blue) should be EPFL red ? 
- Test data color (currently also blue) should be green ?
- Numercial model (currenlty green) should be blue (to match the 3D images blue?)

**Comment by mchaindl** [comment]
@charlottegiseleweil 
### Filter for Numerical models
- Yes, I think is possible to merge both parts. And above that we should include the text that explains briefly what is contained in this tab.
- I think the way you are showing the selector now is very nice :), I like it!
- Yes, "Show only Buildings with numerical models" sounds good.
- I am of the opinion of keeping the numerical models option also in the filter in case the user doesn't see the selector

### Colorscheme coherence
- Yes, Iike that colorscheme, let's see how it looks like
