### ISSUE TITLE
[Feat] Website structure simplification (Resources and Info contents)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#21]
Main menu should be simplified..

Additions 21/5. 

- [x] Book icon (says "Resources" upon hover) : dialog box with Resources (MAST CLI, links to EPFL, EES, ENAC-IT4R)
- [x] "Contact Us" -> "Contact"
- [x] Remove upper left menu icon, or move it below (to the scope "Buildings" only since it's not relevant to "Overview" anymore!

 ### Remove tab "Contact us" ( it doesn't need its all tab for a line of text. )

- [x] Implement Option (1) (Recommended) Remove also the "Resources left-menu, which should be accesible from everwhere, not only from the "Overview tab". Replace it contents by 2 icons on the top left of the website, accessible always:
> - Icon 1 : (?) -> Leads to Intro dialog box
> - Icon 2 : (i) -> Leads to a New dialog box titles "Resources & Contact" containing the Contributors info (MAST CLI, Contact of Katrin and Mathias, links to EPFL, EESD and ENAC-IT4R). 

For reference :
- Option (2) (Minimal change) Move into the "Resources" left-menu which could contain the following : 

> - (i) Introduction -> Leads to Intro dialog box
> - MAST CLI
> - Contact -> Links below to Katrin Beyer and Mathias Haindl
> - EPFL
> - EESD
> - ENAC-IT4R

What do you think @mchaindl ?
 
 ### Clean up toolbar

- [x] Replace 2-lines menu switch to toolbar (https://quasar.dev/vue-components/toolbar) with 2 tabs only : Overview, Buildings.

**Comment by mchaindl** [comment]
### Remove tab "Contact us" ( it doesn't need its all tab for a line of text. )
This sounds good, but I need to check with some users (what they prefer). My only concern is that the "Contact" option will not be visible enough.
I would like to be able to see and compare these two options that you propose before making the decision. Could it be?

### Clean up toolbar
I didn't understand this comment very well :(.

**Comment by charlottegiseleweil** [comment]
@mchaindl ok - let's go with Option 1 for now and see if Users are concerned with not finding the Contact option. It really makes more sense to make these Resources section available from everywhere. 

Clean up toolbar is a note directly for @ymarcon don't worry :)
