### ISSUE TITLE
Overview tab : alignments and new minor fixes

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#26]
- [x] Fix alignments

![OverviewTab_FixAlignment](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/afa35d55-e1d7-4535-ac08-c678a14fd3d9)

![OverviewTab_FixAlignment2](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/37d95d89-64de-4a5a-a1eb-045b7a1e7806)

- [x] To be consistent with the "Buildings" page, let's use the ? icon to show what can be done on the "Overview" page. This way we can save a little bit of space and maybe pull a little bit up the plots:
![OverviewTab_PopUp_Info](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/86ce6d3b-cc5a-4a2b-a67d-fe32eb9b562e)
The text to display could be: "You can select a feature of the buildings to see how they are related to other features. This selection also serves as a filter when you go to the Buildings section (where you can find the complete list of buildings included in this database)
Furthermore, based on your feature selection, you can check the results of a vulnerability analysis by using the toggle "Show vulnerability plots""

- [ ] Add "Contact Us" as a title for the Contact pop-up window:
![Add_ContactUs](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/b8c7cf8a-0de2-4e35-aeb5-785814c5e8d8)

- [x] Overview tab, remove padding or minimize margins to minimze space between doughnut and bottom plots.

**Comment by charlottegiseleweil** [comment]
@mchaindl please make new issues for more minor fixes, so we don't miss any :)

**Comment by mchaindl** [comment]
@charlottegiseleweil Okay, no problem. Thanks
