### ISSUE TITLE
VTK Colors

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#28]
Try to see if it is possible to show the models similarly as is shown here:
https://kitware.github.io/glance/app/
https://github.com/Kitware/paraview-visualizer
https://www.youtube.com/watch?v=UcFWOzG5ygM
This way it would be possible to conserve the different colors for the different elements in the model.

**Comment by mchaindl** [comment]
This is related to https://github.com/EPFL-ENAC/eesd-mast/issues/43. I am moving it there
