### ISSUE TITLE
Various UI adjustments

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#3]
Tested Buildings page:

- [x] Display only the list of tested buildings (experiments)
- [x] Include the Full Reference column (from References table) to the Experiments table (when in table mode)
- [x] Add a References filter in the sidebar: can select multiple references
- [x] Number of storeys and wall leaves filter: allow selections of predefined choices 1, 2, 3...
- [x] Replace filter Applied excitation directions by the Number of simultaneous excitation directions
- [x] Set Reference above the experiment description in cards, dialog, experiment page
- [x] Add Reference details in the Experiment dialog
- [x] Left-menu : Button to "Clear all" selection (Suggested by @ymarcon)
- [x] Table view : add additional column (sortable) : "Year of publication"
- [x] Aesthetic comment : smaller tumbnails to see more building (~5 per row?) => this must be a divider of 12 (2,3,4,6)

Building page:

- [x] Add a shortcut link to paper aside of the Reference name
- [x] All numbers with max 3 decimals
- [x] Display README.md (or any other markdown files) in the Files tab
- [x] Add "Motivation of the test:" before the experiment's motivation text
- [x] Omit experiment fields: Material characterisation, Associated test types, Digitalized data, Experimental results reported, Crack types observed
- [x] Show 3D model in a square
- [x] Set 3D Model tab after the Run Results tab
- [x] Run Results tab to be renamed Test Results
- [x] Do not show Initial and Final rows
- [x] Do not show empty Run Result columns
- [x] In Reference tab, remove Request Data Available and show Link to Request Data only when available
- [x] Rename Link to Request Data as Link to Data
- [x] Replace DG period image by a chart from the run result values: Actual PGA [x,y,z] and DG (reported or derived) vs. Reported TI [x,y,z]
- [x] Modify axis of the 2nd plot (y:PGA, categorical colorscale based on DG)
- [x] Display both PGA X and PGA Y charts when available

Data Submission page:

- [x] Contact us text, with Mathias and Katrin emails
- [x] Add a link to expected data format (readme of the ees-mast-cli ?)
 
Importation:

- [x] Add building height

**Comment by ymarcon** [comment]
@mchaindl I have added the period graphs but still have some questions:

* In case there are both X and Y period data, do we need to make 2 graphs? see https://mast-dev.epfl.ch/building/17
* When there is no Actual PGA, I use the Nominal PGA, is this ok? https://mast-dev.epfl.ch/building/12

**Comment by mchaindl** [comment]
@ymarcon regarding your comments, here are my responses:

- In case both X and Y period data are available (more than 3 values for each one) it would be nice if we can plot both. In case there is less than 3 values for one of the periods, then plotting only the one with more values is okay.
- When there is no Actual PGA, it is okay to use the Nominal PGA.

Is it possible to have a separate plot for Periods and Damage Grade (DG)? 
If yes, in the case of the plot for DG, it would be better if we only show it with circle markers but without lines that connect them (this is only for the plot of DG, not for periods)
