### ISSUE TITLE
Buildings tab: new minor fixes

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#30]
- [ ] ~~There is a problem with the toggle for showing the numerical models that now has 3 positions (one additional in the middle that is showing just one building).~~ **See comment**
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/26080e48-dd99-46be-92d2-bb543032acf0)

- [x] Edit the info pop-up when clicking the ? icon
![BuildingsTab_PopUp_Info](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/1badfc98-0de0-4bea-83b8-68b026c4d1ad)
The added text is: "In addition, by using the toggle “Show only buildings with numerical models” you can check the buildings for which a numerical model is available."

- [x] Freeze the upper part of the searching toolbar so it is always available even when scrolling down:
![BuildingsTab_FreezeTop](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/5e4ea166-4e27-4b36-9805-c5233c4af4b6)

- [x] When selecting some filters and then deselecting them, the complete list of buildings is not shown again. For example, if I select Clay and Stone as Masonry Unit Material and then I deselect them, the full list of buildings is not displayed again. It only happens if I reset all the filters.

- [ ] ~~Make by default that all buildings are shown on the page (I think we can get rid of the "Records per page" given at the end of the page)~~

- [x] Allow to download the table shown in "TEST RESULTS" of each building as a .csv file or .xlsx (only one of these two formats, the easiest). The name of the file should be Author_Year_TestSummary.csv.

- [x] In the details of the test for each building, increase the fontsize of "Motivation of the test" to be the same size as the description given for the motivation.

- [x] In the DETAILS window of the test results for each building, the "First Estimated Fundamental Period" and "Last Estimated Fundamental Period" are not shown correctly. For example, in the case of Beyer et al. (2015) it should be 0.13 sec. and 0.21 sec., respectively. I think this is repeated for all buildings. This is a mistake coming from my excel file of the Database, which I need to fix as well **(I just uploaded an updated version to the shared folder)**.
![BuildingDetails_TestInfo](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/5bdd14b1-b2d3-4a7c-8f00-7b3cc26594f7)

**Comment by ymarcon** [comment]
@mchaindl I cannot reproduce the filter issue (the 3rd item), the issue was fixed yesterday, could you reload the page and try again?

**Comment by mchaindl** [comment]
@ymarcon First I set the "Records per page:" to All. Then, I filtered for Stone and Clay and it shows the buildings correctly. But then if I deselect both filters manually (without using the "Reset filters" button), the full list of buildings is not shown (as it is supposed to be if no filter is applied)

**Comment by ymarcon** [comment]
@mchaindl ah ok it is a matter of pager sync. BTW it is not recommended to show all items by default, as it overloads the servers (especially in this case where there are a lot of images) and it is usually useless (you cannot see more than the page's view port). And also there is a text filter at the top right for the case one would search for a keyword.

**Comment by ymarcon** [comment]
As the filter "Numerical model" was introduced in the Overview page, the toggle in the Buildings page has 3 states:
* left position: without numerical model
* middle position: undetermined (= no filter)
* right position: with numerical model

This is equivalent to a filter made with check boxes and Yes/No options:
* No: without numerical model
* none (or both) selected: no filter (or all filtered)
* Yes: with numerical model

**Comment by mchaindl** [comment]
@ymarcon I think this is a little bit confusing. I will only turn the filter of numerical models on if the "Yes" is selected in the donut chart, but if "No" is selected the filter is not activated and it only serves to show the connections in the parallel plot.
