### ISSUE TITLE
Overview tab: new minor fixes

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#31]
- [x] Increase the font size of "Database Overview" and "Buildings" (I think the size given in the previous version of the web was okay)

- [x] #46

- [x] Since we now have the "How to cite" icon (, it is unnecessary to put the citation again in the welcome message. In addition, please make the font of all this information the same (the same font as it is in the Acknowledgments). Please put the "How to cite" icon at the end of that icon list at the top right of the page.

- [x] Make the titles of the donut charts bold and adjust the width in which the vulnerability plots are shown, like in the following image (it doesn't matter if the plots get narrower):
![VulnearbilityPlots_Width](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/0f4a7c40-afef-46fd-bb67-38becb0a6633)

- [x] Why were the main buttons "Overview" and "Buildings" changed? I think it is a little bit redundant if we use "Masonry Shake Table Database" both for the menu and the title header.
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/0ae84d43-8221-4714-ae83-c8d73df47118)

- [x] Fix misalignment:
![OverviewTab_FixAlignment3](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/20423db9-83ed-4ece-aa64-1178f2a2e205)

- [x] Add photos to Contact Us (**please with the circular format**) **(I added the photos shown here in our shared folder)**:
![New_ContactUs](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/12e7d2b6-5ed9-4371-921e-79bfeacfbc76)

- [x] Add to the stats banner the availability of numerical models in the database. Here is an example of how to put it:
![UpdatedGeneralStats](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/8d8729d0-7f31-474e-81bb-99ff6ea5bb32)

- [x] Does the parallel plot allow for changing the size and font family of bar titles and names?
![OverviewTab_Fontsize_ParallelPlot](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/4da2a4a6-6bc7-4c47-b3cc-599a6b82ff6a)

- [x] #45
![OverviewTab_DonutFilter](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/652cd965-9046-43f5-a544-b69168f262ba)

- [x] Add a fifth donut chart for "Numerical model available" with "Yes" and "No" as selectors. **This additional donut chart should not affect the fragility curves (doesn't affect the vulnerability analysis plots)**

- [x] Adjust the position of "Features of the buildings included in the database" (to the right and a little bit down) and make the ? icon bigger and in red color (same for the ? icon on the "Buildings" page). Also, allow the pop-up message to appear once you place the mouse on it without requiring you to click it.
![OverviewTab_TextPosition](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/c21c3b44-d17e-471c-a70e-0068d5a30e5e)

- [x] Separate a little bit the titles of the donut charts from the donut charts (some of the labels are too close to the titles)

- [ ] Check if possible to keep the "transparent" color of the selected menus/submenus when it is already selected (**please keep the light tone of color when the tab is selected, that way is more intuitive for the user to understand that there is more tabs**). ~~In the case of the submenus (like "Details", "Test Results", "Test Files", "References", etc.) that are in the building details and numerical model pages, make the line under those titles continuous along the whole width of the button~~ (this part is already solved)). Here are some examples:
![Menus_Appereance](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/d806178d-2126-4057-9e57-dedcc4461d6a)

- [x] Change "DB Overview" to "Database Overview". I think DB might not be directly understood as Database.

- [x] Add the "How to cite" at the end of the "Database Overview" page:
![HowtoCite](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/b04ef81f-9e50-4b08-9669-df10b50b7193)
And additionally, we can add an icon on top (where the Contact, Resources, etc. are located) for citation. The icon could be something like this: 
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/6edc1f64-e848-4b4f-bf5f-4a06217e606a)
In addition, the citation could be placed in the welcome pop-up message, like this (I would made this pop-window a little bit wider):
![New_Welcome_Message](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/1c957917-afed-45c4-8f69-5b17c2fd1f24)

- [x] Below the reference given for the fragility curve, add the reference for the definition of the damage grades. The text could be: "Damage grades (DG) defined according the EMS-98 methodology (Grüntal, 1998). The European Macroseismic Scale EMS (https://www.gfz-potsdam.de/en/section/seismic-hazard-and-risk-dynamics/data-products-services/ems-98-european-macroseismic-scale)

- [x] Mention somewhere (to be decided) that fragility plots (also plots in test results of buildings) can be zoom-in and zoom-out.

**Comment by ymarcon** [comment]
First item follows a discussion with @charlottegiseleweil see #29

**Comment by mchaindl** [comment]
@ymarcon @charlottegiseleweil Ahh, I understand. But could it be better if we rename it as "Database Overview" instead of "Masonry Shake Table Database"?

**Comment by ymarcon** [comment]
It could but in this case in the other pages (the ones without a banner image) there will be no recall of the web site name.

**Comment by mchaindl** [comment]
Yes, I agree. However, that is why I want to insist on the idea of considering the second design of the header for the "Buildings" page.
![Website_BuildingsTab_NewDesign_v3](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/fd357d0e-2a5f-4769-ae98-7864836682fc)

**Comment by ymarcon** [comment]
There are also the test and model pages

**Comment by mchaindl** [comment]
Yes, in those cases I would **not** include the header image. So the header images would be included only on the main pages ("Database Overview" and "Buildings")

**Comment by ymarcon** [comment]
Exactly and then there would not be the title "Masonry Shake Table Database" in the test and model pages

**Comment by mchaindl** [comment]
I would say that is not a problem, since at that moment the user already passed through the pages that highlight the main title and we will have the "Database Overview" button at the top, which also refers to the database.

**Comment by ymarcon** [comment]
I was thinking of the case someone makes a screenshot and include it in a presentation, it is better to have the website title in all pages. @charlottegiseleweil ?

**Comment by charlottegiseleweil** [comment]
Good discussion to streamline the design !!

I agree that it'll be more consistent to have the banner in both main page and the same top-menu with "DB Overview" and "Buildings" as tabs.  

I don't think it's a problem to not have the title in the sub-pages indeed. (People put titles if they do screenshots so I wouldn't worry about that...)

**Comment by ymarcon** [comment]
I am closing this issue. I know you updated/added some tasks, but please open another one if it still makes sense, otherwise it is confusing with the issue tracking.
