### ISSUE TITLE
GUI: move from one choice to another (material, floors, etc.)

### ISSUE THREAD

**Issue by SavvasSal** [EPFL-ENAC/eesd-mast#37]
Once you select a material, diaphragm, etc. all the other options of the same category disappear. It would be good if you leave the rest of the options as tick boxes still visible on the side (and possible to add/remove).

**Comment by mchaindl** [comment]
I think this is related to allowing more than one filter for each donut chart. This is already included in https://github.com/EPFL-ENAC/eesd-mast/issues/31. I am closing this here
