### ISSUE TITLE
Overview tab : Vulnerability plots 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#38]
suggestion from Katrin :  Histograms instead of KDE ? Or mention that they are KDE

**Comment by ymarcon** [comment]
@mchaindl what is the decision?

**Comment by mchaindl** [comment]
@ymarcon It would be better if they are shown with histograms, but I don't know if it is possible. If it is not possible then we should mention that the curves correspond to "kernel density estimations" truncated at the extreme data. If it can be shown like the following picture, it would be great:
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/b148f2f8-821b-4e8e-b712-f1c4ee2ea7b9)
