### ISSUE TITLE
Text fixes 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#4]
Building view :
- [x] Rename "Building Height" and "Building Height (without roof structure)" to precise.
- [x] Rename axis of both plots.
- [x] Table headers.

**Comment by mchaindl** [comment]
@ymarcon As a reference, I am attaching the corrections that should be made in the plots shown in the details of each building (thess are the corrections we discussed in our last meeting).
![Fix_BuildingDetails](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/41b4ee2b-bc7e-49e0-8d44-1830b95d0b01)

**Comment by ymarcon** [comment]
FYI some experiments have a DG 5, which color is currently purple:
https://mast-dev.epfl.ch/building/42
https://mast-dev.epfl.ch/building/55

**Comment by ymarcon** [comment]
No mention whether it is an actual/nominal PGA?

**Comment by mchaindl** [comment]
Yes, purple is okay for DG 5

**Comment by ymarcon** [comment]
In the overview the colors are:
* DG 1 blue
* DG 2 green
* DG 3 yellow
* DG 4 orange
* DG 5 red

**Comment by mchaindl** [comment]
That's true, let's keep them like that:
- DG 1 blue
- DG 2 green
- DG 3 yellow
- DG 4 orange
- DG 5 red
