### ISSUE TITLE
Highlight availaibility of numerical models

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#40]
Maybe another donut plot with "Numerical models available "Yes/no" ? 
Without duplicating entry points !

**Comment by mchaindl** [comment]
I also moved this to https://github.com/EPFL-ENAC/eesd-mast/issues/31. Closing the issue here

**Comment by mchaindl** [comment]
I also moved this to https://github.com/EPFL-ENAC/eesd-mast/issues/31. Closing the issue here
