### ISSUE TITLE
Numerical models : 3D visualization

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#43]
- [x] Change the default angle and make it more obvious that user can interact with the 3D viz

- [x] Add acknowledgment to Jose Gallardo for developing the code to generate the .vtk files with the geometry of the models.
The text could be placed right below the model scheme and .vtk visualizer and could say: "The codes for generating the .vtk files for visualizing the geometry of the equivalent frame model were developed by Jose Gallardo Briones at EESD."

- [ ] Try to see if it is possible to show the models similarly as is shown here:
https://kitware.github.io/glance/app/
https://github.com/Kitware/paraview-visualizer
https://www.youtube.com/watch?v=UcFWOzG5ygM
This way it would be possible to conserve the different colors for the different elements in the model.

- [x] Add a note to highlight that you can zoom, rotate, and hover over the numerical model (.vtk visualizer)

**Comment by ymarcon** [comment]
I tried to set colors, without success... partly because the color criteria is unknown (should be in the source file)

**Comment by mchaindl** [comment]
Is it possible at least to show the models with the "Surface with Edges" mode?
