### ISSUE TITLE
How to cite part at the end of the main page

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#46]
Please present the "How to cite" part at the end of the main page in a similar format as it is in the https://resslab-hub.epfl.ch/

**Comment by ymarcon** [comment]
@mchaindl I do not see the citation instructions in Resslab.

**Comment by mchaindl** [comment]
@ymarcon Sorry, it was my mistake. The format I was referring to is the Copyrights one at the end of the main page of Resslab.

**Comment by ymarcon** [comment]
@mchaindl Do you want a citation or a copyright notice? Please provide the text (you can use markdown format).

**Comment by mchaindl** [comment]
@ymarcon A citation notice with a similar format as the Copyrights given in the resslab database.
Should we also give a Copyright notice in our case somewhere?

**Comment by ymarcon** [comment]
Sorry to insist but please provide the text you want to see and I'll include it.

**Comment by mchaindl** [comment]
Sorry, here is the text and how I am thinking it should look like.

"For any research, publication, or presentation that utilizes data from this database and/or the references used here, please ensure to acknowledge and cite the sources appropriately. Please cite this database as follows:

Haindl, M., Beyer, K., & Smith, Ian F. C. (2023). A database of shake-table tests conducted on unreinforced masonry buildings. Submitted to Earthquake Spectra
Haindl, M., Beyer, K., & Smith, I. F. C. (2023). A database of shake-table tests conducted on unreinforced masonry buildings (Version v2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11093882"

![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/482f7a15-82cb-4e0e-8f04-7ea733aa9755)

**Comment by ymarcon** [comment]
So it is basically the same as it is today, without the colors?
