### ISSUE TITLE
Overview tab : Remove 5th Donut plot

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#49]
Following up on the issue #30 :
@mchaindl we've taken  deeper look at this, from a UX perspective. 

Agreed that it doesn't work for the user to have 3 states for the toggle "Filter numerical models" in the buildings tab. 

**However, can we re-question the relevance of the 5th donut chart (Numerical models available) ?** 
It is not great for 2 reasons on the UX side : 
 (1) 5 donut charts is too much in width and breks the natural balance of the design (it should always be a multiple
Is it really of 3 or 4)
 (2) a donut chart with 2 categories is often irrelevant from a dataviz perspective
 
 So let's think about  why is this 5ht donut herem and propose solutions :
 (a) Is this information (proportion of Numerical models available) what you want to display? 
 --> If yes: then I recommend we just add this (dynamically udpated) number (now 34%) in the header that say "Numerical models available" 
 
 (b) Is this donut here so you can filter with the other donuts on the Avaialability of numerical models ?
 --> If yes, then I suggest we add the toggle "Show only numerical models available" (with only 2 states, as it was originally), in the Overview tab, next to the toggle "Show vulnerbility plots". It will be the same as in the Buildings tab so very coherent :) 
  
 We can of course do both (a) and (b) but let's remove the 5th donut plot ok?

**Comment by mchaindl** [comment]
@charlottegiseleweil Thanks for the comment and discussion. Let me try to answer your questions and doubts:
(a) Is this information (proportion of Numerical models available) what you want to display?
Answer to (a): Yes, this is actually the important information, apart from showing that our database also includes numerical models. For the user it is very important to realize from the beginning that there is numerical models available. 
If we add a dynamic counter in the header I think it should say "XX% of buildings with ready-to-use numerical models" (or something similar). The number 69 for "Tests on unreinforced masonry buildings" should also be a dynamic one.

(b) Is this donut here so you can filter with the other donuts on the Avaialability of numerical models ?
Answer to (b): It would be nice to see in the parallel plot what are the characteristics of the buildings for which the models are available (that was the reason of having the donut chart there). But I agree that there is not so much that this donut chart adds to the visualization. But as I said, is very important that the user knows from the beginning that the database includes numerical  models that can be downloaded.

So, okay, let's remove the 5th donut but let's add the statistic in a dynamic way in the header stats.

**Comment by charlottegiseleweil** [comment]
Okay, how about :
- [x] Dynamic number (4th): "XX% buildings with numerical models"
- [x] Dynamic number (1st)The number 69 for "Tests on unreinforced masonry buildings" should also be a dynamic one
- [x] Add a line dyanmically mentioning the number of test in the selection (@mchaindl it's really not a good idea to update the header based on filters. It's all dynamic based on overall DB contents, but the filters only update the selection, which we add a line for summairzing the # of buildings and numerical models selected)
- [x] Adding "Numerical model available" column in paralell coords plots

**Comment by ymarcon** [comment]
@mchaindl please see what it looks like now https://mast-dev.epfl.ch/

**Comment by mchaindl** [comment]
I added some comment in https://github.com/EPFL-ENAC/eesd-mast/issues/51
