### ISSUE TITLE
Add separate 3D models (numerical models)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#5]
- [x] Rename "Tested Buildings" tab "Buildings"
- [x] In Buildings tab : Add little SVG as icon on the buildings with numerical models. 
- [x] In Building tabs add legend "Buildings with sim. models
- [x] Additional filter "Show numerical models only"
- [x] Pop-up upon click on Building should be simplified (no scrolling) : only Title+reference to paper + 2 buttons with images : (1) See experimental results (with picture of building) (2) See numerical model (with image SVG of numerical model)

Building view:
- [x] Add plan view of the building image (under the building picture)
- [x] Provide additional data for 3D model -- to investigate if color legend is possible (red for rigid elements, blue for modular elements

**Comment by mchaindl** [comment]
@ymarcon @charlottegiseleweil Regarding the data for the 3D models, we discussed here at EESD that it would be a good idea to take the 3D models out of the detailed information of each building.
It is better if we have an additional tab in the main page called "Numerical models". This may look similar to the "Tested Buildings" section.
I am attaching an example of how we think this might look like.
Let me know what do you think :)
![NumericalModels](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/fc054437-6699-45c3-8e45-a2aa921748d2)

I can provide the pictures for all the models that I already built.

**Comment by ymarcon** [comment]
What happens when clicking on an item? Does it go to the building page or to a "3D model" page that is somehow linked to the building page?

**Comment by mchaindl** [comment]
It should open a window similar to when you click on one of the tested buildings, but here we will have the information about the assumptions of the models and the possibility to download it. 
I think it would be nice to also include in that window a link to the corresponding building in the tested buildings in order to allow the user to go directly to the experimental results.
The same can be done when clicking on one of the tested building, so you can click somewhere to go to the model directly.

**Comment by ymarcon** [comment]
I would need more specifications of what would be "the information about the assumptions of the models". At least one complete example with the 3D model file and its meta information.

**Comment by charlottegiseleweil** [comment]
As discussed today - it's be great @mchaindl if you can come up with a few user stories of use cases fo the tool (bullet points are fine!) so we can ensure the overal structure of the website makes sense instead of duplicating features and adding a new tab with each new idea ^^
