### ISSUE TITLE
Overview Tab: minor changes

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#51]
- [x] Enclose the "How to cite" part at the end of the page. Use a similar frame as the one used in Copyrights for Resslab. 

- [x] Put "For any research, publication, or presentation that utilizes data from this database and/or the references used here, please ensure to acknowledge and cite the sources appropriately. Please cite this database as follows:", just in one line.

- [x] Reduce the length of the lines that connect the names of the categories in each donut chart, they are using too much space. Make the names of the categories to be closer to their corresponding donut chart.

- [ ] Make the titles of each stripe (Masonry mat., Unit type, Diaph. mat., etc.) in the parallel plot bold and add some space between the title and the stripes. Also increase the fontsize of the names included in each stripe (Adobe, Stone, Solid brick, etc.) bigger.

- [x] I don't see this change implemented, the vulnerability plots are still using almost the whole width of the webpage.
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/ae82e1aa-78a1-4cc2-bce3-f771eb3e525b)

- [x] In the dynamic counter for the numerical models modify it as (round the percentage to the closest lower integer): 
XX% of buildings (bolded part)
with numerical model available for downloading

**Comment by ymarcon** [comment]
No success with styling plotly labels: limited possibilities and some are not working.
