### ISSUE TITLE
Parallel plot labels and visualization of "How to cite" box

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#57]
Please increase the size of the font in the labels of the parallel plot.
In "How to cite" box at the end, please reduce the space between lines and also make the bottom line of the box visible.
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/c5a43e9f-c6cb-4540-94f3-ca93f556f92d)
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/cbf3ca2d-2996-49fe-a718-db082cf20ea4)

**Comment by ymarcon** [comment]
Sorry but I already tried to style of the parallel chart without success.

**Comment by mchaindl** [comment]
@ymarcon Ahh okay understand, I thought the fontsize was still possible.
In addition, is it possible to make the vulnerability plots appear by default with this space between the axis line and the ticks (as shown in the figure below)? Because it only happens now if I double-click in the white area inside the plots, but it looks nicer this way.
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/5b61ffe7-0a3d-4d6e-939e-a67edd88d64c)

**Comment by mchaindl** [comment]
@ymarcon I found this (https://plotly.com/python/parallel-categories-diagram/), that maybe could help to solve the issue of the fontsize? I am not sure if can be applied to our parallel plot:
fig = go.Figure(data = [go.Parcats(dimensions=[class_dim, gender_dim, survival_dim],
        line={'color': color, 'colorscale': colorscale},
        hoveron='color', hoverinfo='count+probability',
        labelfont={'size': 18, 'family': 'Times'},
        tickfont={'size': 16, 'family': 'Times'},
        arrangement='freeform')])
