### ISSUE TITLE
Details info for each building

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#58]
I noticed some information is not displayed correctly (I took an example of the Beyer et al. 2015 building). For example, the wall thickness is shown as "undefined" and it should say 95 mm. Please, also change the name of the rows "Link to Open Measured Data" --> "Link to Digital Experimental Data" and "Roof Material Geometry" --> "Roof Material and Geometry"
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/0e09eef1-d575-4891-9c14-7970de62f8c3)

**Comment by ymarcon** [comment]
Please reload page, I do not see the wall thickness error:
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/2581149/d2c5ad74-899e-47b9-bcc0-f98abaa54bee)

**Comment by mchaindl** [comment]
@ymarcon Yes, I don't see the "Wall thickness" error anymore. Thanks

**Comment by mchaindl** [comment]
@ymarcon Instead of naming the tab as DETAILS (the first tab in the building's specific info), could we please change it as SUMMARY?

**Comment by mchaindl** [comment]
@ymarcon Apart from changing the DETAILS name to **SUMMARY**, and changing the row titles of "Link to Open Measured Data" (to "**Link to Digital Experimental Data**") and  "Roof Material Geometry" (to "**Roof Material and Geometry**"), I also found in the numerical model part a missing letter in the "Modeling approach". It should say **Equivalent frame model (EFM)** instead of Equvalent frame model.
