### ISSUE TITLE
Deactivate for the moment the numerical models (coming soon)

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#59]
@ymarcon @charlottegiseleweil At EESD we have been discussing that, for the moment (at least for the first launch of the website), it is better to keep the numerical model option deactivated, mainly because we still need to check the models more carefully, and also I have made a couple of changes on a few of them. 
In that sense, is that possible for the moment to keep seeing that there are numerical models available but without allowing the user to access or download them?

**Comment by ymarcon** [comment]
Sure, it is possible. Do you have an estimated date for the numerical models to be ready?

**Comment by mchaindl** [comment]
Not sure yet, but I am trying to do my best to have it as soon as possible. I would say by early August they should be ready.

**Comment by ymarcon** [comment]
And do you plan to communicate about the website before the numerical models are ready? Otherwise we can just wait.

**Comment by mchaindl** [comment]
Yes, is okay if they are not ready because this is really a nice effort we are doing in terms of sharing numerical models. This is normally not done.

**Comment by ymarcon** [comment]
I meant if there is no rush, we could spare the dev time spent to hide things temporarily.

**Comment by mchaindl** [comment]
I am not sure what do you mean, but hidding this info temporarily is okay for me. I am not sure if I am answering your question.

**Comment by ymarcon** [comment]
It takes dev time to hide things, and there is just a few hours remaining for the project (and there is still substantial work to do), so if we can avoid this work by delaying the website publication until the numerical models are ready, it is better. Anyway, it is a project management issue and I'll check with @charlottegiseleweil.

**Comment by charlottegiseleweil** [comment]
Dear @mchaindl  - apologies for not following closely the recent issues as I'm on vacations.

However, the official project end date was June 30th, so no new features will be implemented at this stage. You're welcome to continue adding issues as suggestions for future improvements here, but they will be tagged "wontfix" for the moment.

We of course remain available for small quick fixes (typos etc), as part of the maintenance, but if you request new features, we'll need to discuss how to frame a second phase of this work !

Let's discuss this in more details in our scheduled closure meeting in 10 days, and adjust as necessary then. But until then, @ymarcon is now busy on other fronts !

Looking forward to our closure meeting to address all these, and wishing you a great week till then
