### ISSUE TITLE
Overview tab (including Vulnerability Analysis)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#6]
2 sections in one"General" and "seismic" with several plots and automated select/filtering between all. 

- [x] @mchaindl to provide the final mock-up of the Overview tab (and feel free to ping me to review it together ;) )

Feedback / additions from @mchaindl  on the donut plots : 
- [x] Remove the legend below and have labelLines instead 
- [x] Button "See corresponding Buildings" --> Bottom right of Overview tab to link directly to Tested Buildibgs tabs, keeping the preselections. 
- [x] Masonry Unit Material column : Pre-process the data to merge all the "stones" options, as in the sketch.  
- [x] Diaphragm Material column : Pre-process the data to merge all the "mixed" options, as in the sketch. 
- [x] Colorscales update - to be precised by @mchaindl 
-Masonry Unit Material Colors : Clay red ; Stone blue 
-Diaphragm : timber : brown ; bricks : orange etc.. 

- [x] Change middle number to 100+ "References"

Vulnerability Analysis

- [x] Button "Check Vulnerability Analysis" top right, open a right panel with the 2 plots of vulnerability analysis

**Comment by mchaindl** [comment]
@charlottegiseleweil @ymarcon Here I am attaching the mock-ups of the "Overview" tab.
We discussed this here at EESD and we came up with an idea like the one I am attaching.
Please let me know what do you think and if the idea and features that I want to show are clear.
Thanks
![Overview_MockUP_1](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/8ed7fde1-78eb-42bf-b42e-a0035b0e276b)
![Overview_MockUP_2](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/33658bfe-8c0c-4d38-8325-e5bd658cb999)

**Comment by ymarcon** [comment]
@mchaindl Regarding the vulnerability analysis charts:

* some experiments can have PGA vs DG for different directions (x, y, z),
* some are based on actual PGA while others are on the nominal one
* some are based on the reported DG, while others are on the derived one.

What are the rules about the directions, actual/nominal, reported/derived characteristics for aggregating these information into these charts?

**Comment by mchaindl** [comment]
@ymarcon Yes, so the vulnerability charts should be generated as follows:

If a PGA is given for different directions, then always the maximum is taken (actual PGA have always priority over nominal PGA)
If the actual PGA is not given, then only in this case the nominal PGA is used (the maximum if more than one direction is given)
Regarding the DG, always the one available should be used. I think there is no case where a reported and derived DG are given at the same time (I need to double-check that)

There is no rule about the directions, so always the maximum PGA needs to be taken (in case more than one direction is given), and the DG should be only one (the reported or derived depending on which is available)

Thanks

**Comment by ymarcon** [comment]
About color schemes:

* use different colors for each filter, either distinct categorical values for masonry and diaphragm, or gradient for storeys and scales
* do not change color of on click of the donut slice

**Comment by ymarcon** [comment]
Reuse selected filters in overview page to list the corresponding buildings.

**Comment by ymarcon** [comment]
Plotly provides parallel plots with categories
https://plotly.com/javascript/parallel-categories-diagram/

```
postgres=# select masonry_unit_material, diaphragm_material, storeys_nb, test_scale, count(*) as count 
  from experiment
  group by masonry_unit_material, diaphragm_material, storeys_nb, test_scale
  order by masonry_unit_material, diaphragm_material, storeys_nb, test_scale;

 masonry_unit_material | diaphragm_material | storeys_nb | test_scale | count 
-----------------------+--------------------+------------+------------+-------
 Adobe                 |                    |          1 |       0.25 |     1
 Adobe                 |                    |          1 |      0.667 |     1
 Adobe                 |                    |          1 |          1 |     1
 Calcareous sandstone  | RC & Timber        |          2 |          1 |     1
 Calcareous sandstone  | Timber             |          2 |        0.5 |     1
 Calcareous sandstone  | Timber             |          2 |          1 |     2
 Calcareous sandstone  | Timber             |          3 |        0.5 |     1
 Calcareous tuff stone | Timber             |          2 |      0.667 |     1
 Calcium silicate      | RC                 |          1 |          1 |     1
 Calcium silicate      | RC                 |          2 |          1 |     3
 Clay                  | Hollow tile slab   |          2 |          1 |     1
 Clay                  | RC                 |          1 |        0.5 |     3
 Clay                  | RC                 |          2 |       0.25 |     1
 Clay                  | RC                 |          2 |          1 |     2
 Clay                  | RC                 |          4 |        0.5 |     1
 Clay                  | RC                 |          5 |       0.25 |     1
 Clay                  | Steel & bricks     |          1 |      0.667 |     1
 Clay                  | Timber             |          1 |          1 |     3
 Clay                  | Timber             |          2 |       0.25 |    10
 Clay                  | Timber             |          2 |        0.5 |     5
 Clay                  | Timber             |          2 |          1 |     2
 Clay                  |                    |          1 |       0.25 |     1
 Clay                  |                    |          1 |        0.5 |     1
 Clay                  |                    |          1 |          1 |     4
 Concrete              | RC                 |          2 |        0.5 |     2
 Concrete              | Timber             |          2 |          1 |     1
 Concrete              |                    |          1 |       0.25 |     1
 Granite               | Timber             |          2 |        0.5 |     1
 Granite               |                    |          1 |          1 |     2
 Limestone             | Timber             |          2 |        0.5 |     6
 Limestone             | Timber             |          2 |      0.667 |     2
 Limestone             | Timber             |          4 |      0.333 |     1
 Limestone             |                    |          1 |      0.667 |     1
 Limestone             |                    |          1 |          1 |     1
 Neopolitan tuff stone | Timber             |          1 |        0.5 |     1
 Tuff stone            |                    |          1 |          1 |     1

```

**Comment by charlottegiseleweil** [comment]
Would something like this be okay instead of the violin plots for PGA vs Damage Grade ? <img width="568" alt="Screenshot 2024-04-08 at 15 42 59" src="https://github.com/EPFL-ENAC/eesd-mast/assets/18381609/c66ad0c5-ec03-4a5f-ada1-a815d9f12edb">

**Comment by mchaindl** [comment]
@ymarcon @charlottegiseleweil Regarding the color schemes for the overview tab, here is the list:

**Masonry Unit Material**
Clay: red
Stone: blue
Calcium silicate: green
Concrete: grey
Adobe: orange

**Diaphragm type**
RC: grey
Timber: brown
Mixed: yellow
N/A: purple

For the number of storeys and scale of test, in reality it doesn´t matter that much the colors we use. But I would say it is better if we use like an "ascending" color palette (something like the one in this link for example: https://www.color-hex.com/color-palette/1025944)

**Comment by mchaindl** [comment]
@ymarcon Regarding the violin plots, I uploaded to our shared drive the Jupiter notebook that I generated at some point with these plots (Read_Database_(donnut_violin_plots).ipynb). However, this Jupiter notebook should be used only as a reference, because the database that is loaded within the notebook is an old version that reads a .mat file (this is the old way I used to read the database)

Please let me know if that is okay of you need the jupiter notebook to be working with the current version of the database.

**Comment by ymarcon** [comment]
@mchaindl in the fragility curves, 
1. what is the difference between the solid and the dotted lines ?
2. how do you calculate **P(DGi I PGA)** ?

**Comment by mchaindl** [comment]
@ymarcon 
1. The dotted lines are not required. The idea of using two types of lines was in vase the user can select more than pne material for example, but I think it will be much more difficult if we continue in that way. Maybe it is better if we allow the user to select only one feature from each of the donnut plots. The idea is to show dots (diacrete values from the database) and the continuos line (adjusted function) as in the figure below:

![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/6cb01db6-706d-472f-8996-06ee44246fe0)

2. To calculate P(DGi I PGA) you need to count the number of times a DG is observed at a certain PGA. In the last jupiter notebook that I uploaded (Read_Database_(donnut_violin_plots).ipynb), the function that does that is called “probit_function(IM, p_exceed)”, which is defined in the 4th cell. Then an example of how this curves are computed (for one DG only) is given in “ Figure 6a - Fragility curves for classification based on type of masonry (brick or stone)”. In the jupiter notebook I separate the curves for each DG but the idea is to show the curves for all DGs together (DG1 to DG5 in one plot) in the overview tab.

I know this might be a little bit confusing, so please let me know if there is any doubt.

Thanks
