### ISSUE TITLE
Massive download from "Tested Buildings" tab

### ISSUE THREAD

**Issue by mchaindl** [EPFL-ENAC/eesd-mast#9]
@ymarcon @charlottegiseleweil It would be really useful to have a download link in the "Tested Buildings" to allow the users to download the data from all the filtered buildings directly from here instead of requiring them to go inside of each building.
I am thinking about something like this:
![MassiveDownload](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/384c1c90-dd05-426a-8b82-8ecc1d11a200)

**Comment by ymarcon** [comment]
In which format? the Excel one? What about the associated files?

**Comment by mchaindl** [comment]
> In which format? the Excel one? What about the associated files?

As a .zip file, in which you have a different folder for each building. Each of these folders should contain the experimental results (Crack maps, global force-displacement curve, shake-table accelerations, and Top displacement histories)

The 3D model and Period and DG evolution should not be included anymore as part of the downloadable folders (because they will be shown directly in the window of the details for each building and the 3D models will be moved to the new tab in the main page.

Thanks

**Comment by ymarcon** [comment]
Relates to #7

**Comment by ymarcon** [comment]
@mchaindl Shall the README and License files (if any) be included in this zip?

**Comment by mchaindl** [comment]
@ymarcon Yes, it is better if we include them.
